### ISSUE TITLE
Strange image/animation artefact on large screen Androids

### ISSUE THREAD

**Issue by n3o59hf** [robovm/robovm-store-app#30]
![screenshot_2015-11-02-14-59-34](https://cloud.githubusercontent.com/assets/408236/10888636/09731a2e-8196-11e5-8346-e6f63cb52bf0.png)

Android 5.1, Sony Z Ultra (custom ROM)
Problem is not visible on other devices where size/color selection takes larger relative space.

**Comment by ntherning** [comment]
Thanks for the bug report!
